services:
  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=root
      - POSTGRES_DB=task_manager_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d taskmanager"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: